### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pinloop** [brentvollebregt/spotify-lyrics-viewer#20]
Possible to add option for auto scroll? So the screen auto scroll the lyrics.

**Comment by brentvollebregt** [comment]
Check out #4

**Comment by pinloop** [comment]
> Check out #4

I saw that thread about timestamped scrolling, but I was just thinking about a timer that scroll a line every fre sec or something.

**Comment by brentvollebregt** [comment]
I feel like that would be really annoying. Imagine scrolling down to the part you're on and then it starts scrolling automatically. 

Also it will be very rare that the auto-scroll would match the position of the lyrics in the song.

**Comment by pinloop** [comment]
> I feel like that would be really annoying. Imagine scrolling down to the part you're on and then it starts scrolling automatically.
> 
> Also it will be very rare that the auto-scroll would match the position of the lyrics in the song.

I was thinking about an option where you can change the scroll speed, but maybe you’re right :)

**Comment by brentvollebregt** [comment]
I like your thinking but most cases will not have a one-speed that fits the whole song - I think this may get in the way than be of assistance

**Comment by lhrolim** [comment]
Hi @brentvollebregt I have developed the autoscroll and the lyric synchronization on a fork just for fun and my own sake. I am using it on my recently bought Tesla ;) 

Happy to share a PR code if you feel like, I have a sense I'd need only to polish a bit as I had some issues with subdirectories once I deployed it.

Let's sync.

**Comment by brentvollebregt** [comment]
Closing as this has been implemented in #36
