### ISSUE TITLE
Song title filter feature request

### ISSUE THREAD

**Issue by edilAraujo** [brentvollebregt/spotify-lyrics-viewer#35]
I see you're removing 'feat.' (and things like that) from song titles but can we also remove things like ' - 2013 Remaster' or '(2018 Remaster)?

**Comment by brentvollebregt** [comment]
True, that can be done - I'm happy to take a look at any PRs for this!

**Comment by brentvollebregt** [comment]
Implemented in 8c0d265a5e80dd59138f655107a8d7fb2bbcc709
