### ISSUE TITLE
Can't edit styles using css, request a "settings" function to edit text size, color, etc.

### ISSUE THREAD

**Issue by ParanormalBanana** [brentvollebregt/spotify-lyrics-viewer#41]

**Comment by brentvollebregt** [comment]
Would it make it easier if we put classes on elements? So then you have something for external styles to look select on.

**Comment by ParanormalBanana** [comment]
Yes, either that so I can edit them myself, or a styles editor as a menu
(this is not required for me but would be useful for other people who can't
use css scripts themselves)

If you can do it I will really appreciate:)

**Comment by brentvollebregt** [comment]
I've just pushed I've just pushed 8acde0f to add some ids that can be used.

I'm not planning on adding a styles editor in the application right now.

**Comment by ParanormalBanana** [comment]
Nice, thanks

________________________________
De : Brent Vollebregt ***@***.***>
Envoyé : jeudi 5 décembre 2024 20:29
À : brentvollebregt/spotify-lyrics-viewer ***@***.***>
Cc : ParanormalBanana ***@***.***>; Author ***@***.***>
Objet : Re: [brentvollebregt/spotify-lyrics-viewer] Can't edit styles using css, request a "settings" function to edit text size, color, etc. (Issue #41)


I've just pushed I've just pushed 8acde0f<https://github.com/brentvollebregt/spotify-lyrics-viewer/commit/8acde0fda7f9fd562853d6b4e18f6409b07e181a> to add some ids that can be used.

I'm not planning on adding a styles editor in the application right now.
