### ISSUE TITLE
Two small feature requests)

### ISSUE THREAD

**Issue by FiftyFour7250** [brentvollebregt/spotify-lyrics-viewer#5]
Hey. Can you please add dark theme? And please, pin the player bar, cause right now it's it's a little inconvenient, when you read the last verse, want to pause - and have to scroll to the top. Hope you know what I mean))

**Comment by brentvollebregt** [comment]
Was looking into a dark theme but since I'm using Bootstrap it's not too easy to get everything done. Material-ui could be an option but that would require a decent amount of changes.

In terms of the player bar, I like the idea but do you have a library I could use?

**Comment by FiftyFour7250** [comment]
Yea, there are many libraries in my city))))
Man, I'm not a programmer, sorry, can't help you. Just another lazy user)

**Comment by brentvollebregt** [comment]
The current song controls are now on the bottom of the screen and I have implemented a dark mode. 
Had to completely refactor the layout logic but I got there in a reasonable amount of time 👍

**Comment by FiftyFour7250** [comment]
Really glad to hear that. I wanted to try it, but it absolutely doesn't work for me now :c
I get an error after logging in. Deleting cookies and your app in the spotify settings didn't do anything(

![3](https://user-images.githubusercontent.com/78786088/111010235-f4373280-83a6-11eb-8ecd-2614eebfa740.JPG)

**Comment by brentvollebregt** [comment]
Clearing your cookies should have fixed this which is a bit concerning. I just pushed some new code that clears the Spotify token if it is not giving us the data we want. Give it another shot.

**Comment by FiftyFour7250** [comment]
Same. I get it on my iPad too. Maybe something with my account?... 

No. I get an error on an empty account too

**Comment by brentvollebregt** [comment]
Are you blocking cookies by any chance? I just tried to use this tool in a Chrome incognito window and it failed the same way because cookies were not being sent.

**Comment by FiftyFour7250** [comment]
No, I don't think so. I disabled ad block, I don't have antivirus, I even tried microsoft edge. And as I said - on iPad, in safari - the same thing. I don't know, maybe you should try deleting cookies, or try a few other browsers to figure out what the problem is...

**Comment by FiftyFour7250** [comment]
Screenshot from console, maybe this will help...

![йц](https://user-images.githubusercontent.com/78786088/111014527-19cb3880-83b5-11eb-96b2-41d6ecba86f4.JPG)

**Comment by brentvollebregt** [comment]
That seems like a different issue to the "Error when fetching your profile" issue - did you manage to get further?
I have released a new version that should fix the error you provided above - that was very helpful thank you.

**Comment by FiftyFour7250** [comment]
Yea, it's fixed, thank you)
